#Create connection mysql database get keys from envirmonment
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/saga_sale
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:example}
  jpa:
    hibernate:
      ddl-auto: update
